# ITEM_TREE 테이블에서 PARENT_ITEM_ID에 없는(NULL 포함) ITEM_ID를 구해서 ITEM_INFO와 조인
# SELECT ITEM_ID
# FROM ITEM_TREE
# WHERE PARENT_ITEM_ID IS NULL
#     OR ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE)

SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B
    ON A.ITEM_ID=B.PARENT_ITEM_ID
WHERE B.ITEM_ID IS NULL
ORDER BY 1 DESC