SELECT A.PRODUCT_CODE, B.SUM_SALES_AMOUNT*A.PRICE AS SALES
FROM PRODUCT A JOIN 
    (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM_SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) B
        ON A.PRODUCT_ID=B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC