SELECT DISTINCT
    A.CAR_ID,
    A.CAR_TYPE,
    A.DAILY_FEE * (1-C.DISCOUNT_RATE/100) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE A.CAR_ID = H.CAR_ID
        AND START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
    )
    AND C.CAR_TYPE IN ('세단', 'SUV') AND C.DURATION_TYPE = '30일 이상'
    AND 500000 <= A.DAILY_FEE * (1-C.DISCOUNT_RATE/100) * 30 
    AND A.DAILY_FEE * (1-C.DISCOUNT_RATE/100) * 30 < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC
    