SELECT T.ID, 
(CASE
    WHEN T.NT = 1 THEN 'CRITICAL'
    WHEN T.NT = 2 THEN 'HIGH'
    WHEN T.NT = 3 THEN 'MEDIUM'
    WHEN T.NT = 4 THEN 'LOW'
END) AS 'COLONY_NAME'
FROM(
    SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS NT
    FROM ECOLI_DATA
) AS T
ORDER BY ID ASC