SELECT CAR_ID,
    MAX(CASE
        WHEN DATE('2022-10-16') BETWEEN START_DATE AND END_DATE THEN '대여중'
        ELSE '대여 가능'
    END) AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

# SELECT
#     CAR_ID,
#     IF 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 
# SELECT CAR_ID, START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE <= DATE('2022-10-16') 
#     AND DATE('2022-10-16') <= END_DATE
# ORDER BY CAR_ID