SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM (SELECT B.ITEM_ID
        FROM ITEM_INFO A JOIN ITEM_TREE B
            ON A.ITEM_ID=B.PARENT_ITEM_ID 
        WHERE A.RARITY='RARE') T 
        JOIN ITEM_INFO I
            ON T.ITEM_ID=I.ITEM_ID
ORDER BY ITEM_ID DESC