SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CHILD, ECOLI_DATA PARENT
WHERE PARENT.ID = CHILD.PARENT_ID AND
    CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC