SELECT YEAR(B.DIFFERENTIATION_DATE) AS YEAR, 
((SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA AS A
        WHERE YEAR(A.DIFFERENTIATION_DATE) = YEAR(B.DIFFERENTIATION_DATE))-B.SIZE_OF_COLONY) AS YEAR_DEV, 
        B.ID
FROM ECOLI_DATA B
ORDER BY YEAR, YEAR_DEV
