SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID=B.CAR_ID
WHERE CAR_TYPE = '세단' AND SUBSTRING(START_DATE, 6, 2) = '10'
ORDER BY A.CAR_ID DESC