SELECT T1.ID, T2.FISH_NAME, T1.LENGTH
FROM (
    SELECT A.ID, A.FISH_TYPE, A.LENGTH
    FROM FISH_INFO A
    JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO A
        GROUP BY FISH_TYPE
    ) AS B ON A.FISH_TYPE = B.FISH_TYPE
    WHERE A.LENGTH = B.MAX_LENGTH
) AS T1
JOIN FISH_NAME_INFO T2
    ON T1.FISH_TYPE = T2.FISH_TYPE
