SELECT SUM_SCORE AS SCORE, H.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) T JOIN HR_EMPLOYEES H ON H.EMP_NO = T.EMP_NO
GROUP BY H.EMP_NO
ORDER BY SUM_SCORE DESC
LIMIT 1