SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
JOIN BOOK_SALES B
    ON A.BOOK_ID = B.BOOK_ID
WHERE '2022-01-01' <= B.SALES_DATE
    AND B.SALES_DATE < '2022-02-01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY