SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM (
    SELECT 
        FISH_TYPE, 
        (CASE
            WHEN LENGTH IS NULL THEN 10
            WHEN LENGTH <= 10 THEN 10
            ELSE LENGTH
         END) AS LENGTH
    FROM FISH_INFO
) AS T
GROUP BY T.FISH_TYPE
HAVING AVG(T.LENGTH) >= 33
ORDER BY FISH_TYPE
