SELECT
    CASE 
        WHEN (SELECT SKILL_CODE & SUM(CODE) FROM SKILLCODES WHERE CATEGORY='Front End') > 0 
            AND (SELECT SKILL_CODE & SUM(CODE) FROM SKILLCODES WHERE NAME='Python') > 0 THEN 'A'
        WHEN (SELECT SKILL_CODE & SUM(CODE) FROM SKILLCODES WHERE NAME='C#') > 0 THEN 'B'
        WHEN (SELECT SKILL_CODE & SUM(CODE) FROM SKILLCODES WHERE CATEGORY='Front End') > 0 THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS
GROUP BY GRADE, ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID